---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpass-auth
  namespace: {{ .Values.global.namespace }}
  labels:
    app: endpass-auth
    environment: {{ .Values.global.env }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: endpass-auth
  template:
    metadata:
      labels:
        app: endpass-auth
        environment: {{ .Values.global.env }}
    spec:
      containers:
      - name: endpass-auth
{{  . | werf_container_image | indent 8 }}
        env:
{{  . | werf_container_env | indent 8 }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        resources:
          requests:
            cpu: {{ .Values.deployment.resources.requests.cpu }}
            memory: {{ .Values.deployment.resources.requests.memory }}
          limits:
            cpu: {{ .Values.deployment.resources.limits.cpu }}
            memory: {{ .Values.deployment.resources.limits.memory }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          privileged: false

---
apiVersion: v1
kind: Service
metadata:
  name: endpass-auth
  namespace: {{ .Values.global.namespace }}
  labels:
    app: endpass-auth
    environment: {{ .Values.global.env }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: endpass-auth

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: endpass-auth
  labels:
    app: endpass-auth
    environment: {{ .Values.global.env }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  namespace: {{ .Values.global.namespace }}
spec:
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: endpass-auth
          servicePort: {{ .Values.service.port }}