name: tests
on:
  pull_request:
    branches:
      - master
      - release

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
 
    - name: Setup node version
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install packages
      run: yarn install --frozen-lockfile

    - name: Unit tests
      run: yarn test:unit

    - name: Slack notification on success
      uses: rtCamp/action-slack-notify@v2.0.2
      if: success()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_USERNAME: GitHub Actions
        SLACK_COLOR: '#2AD624'
        SLACK_ICON_EMOJI: ':github:'
        SLACK_MESSAGE: '*${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}* - Auth unit tests'
        SLACK_TITLE: 'Tests successful :rocket:'

    - name: Slack notification on failure
      uses: rtCamp/action-slack-notify@v2.0.2
      if: failure()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_USERNAME: GitHub Actions
        SLACK_COLOR: '#EC4926'
        SLACK_ICON_EMOJI: ':github:'
        SLACK_MESSAGE: '*${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}* - Auth unit tests'
        SLACK_TITLE: 'Tests failed :fire:'
