name: pull-pequest review undeployment

on:
  pull_request:
    types: 
    - closed

jobs:
  undeploy:
    name: Undeploy
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'review' )
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Dismiss
      uses: werf/actions/dismiss@master
      with:
        group: 1.1
        channel: beta
        env: review-${{ github.event.pull_request.number }}
        kube-config-base64-data: ${{ secrets.BASE64_KUBECONFIG }}
      env:
        WERF_HELM_RELEASE_STORAGE_NAMESPACE: werf-releases
        WERF_HELM_RELEASE_STORAGE_TYPE: secret
        WERF_NAMESPACE: endpass-auth-review-${{ github.event.pull_request.number }}

    - name: Delete DNS record
      env:
        RESOURCE_RECORD_NAME_AUTH: ${{ github.event.pull_request.number }}-auth.review.endpass.com
        RESOURCE_RECORD_VALUE: ${{ secrets.RESOURCE_RECORD_VALUE }}
      run: |
        aws route53 change-resource-record-sets --hosted-zone-id ${{ secrets.HOSTEDZONE_ID }} \
        --change-batch '{ "Comment": "Testing creating a record set", "Changes": [ { "Action": "DELETE", "ResourceRecordSet": { "Name": "'"$RESOURCE_RECORD_NAME_AUTH"'", "Type": "CNAME", "TTL": 120, "ResourceRecords": [ { "Value": "'"$RESOURCE_RECORD_VALUE"'" } ] } } ] }'

    - name: Slack notification on success
      uses: rtCamp/action-slack-notify@v2.0.2
      if: success()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_USERNAME: GitHub Actions
        SLACK_COLOR: '#2AD624'
        SLACK_ICON_EMOJI: ':github:'
        SLACK_MESSAGE: 'Success :rocket:'
        SLACK_TITLE: 'Review environment removal status:'

    - name: Slack notification on failure
      uses: rtCamp/action-slack-notify@v2.0.2
      if: failure()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_USERNAME: GitHub Actions
        SLACK_COLOR: '#EC4926'
        SLACK_ICON_EMOJI: ':github:'
        SLACK_MESSAGE: 'Failed :fire:'
        SLACK_TITLE: 'Review environment removal status:'
