name: release build
on: 
  push:
    branches:
      - release
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
  
    - name: Setup node version
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install packages
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build

    - name: Slack notification
      uses: rtCamp/action-slack-notify@v2.0.2
      if: success()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_USERNAME: GitHub Actions
        SLACK_COLOR: '#2AD624'
        SLACK_ICON_EMOJI: ':github:'
        SLACK_MESSAGE: 'Auth (release) build'
        SLACK_TITLE: 'Build succeeded :rocket:'

    - name: Slack notification
      uses: rtCamp/action-slack-notify@v2.0.2
      if: failure()
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_USERNAME: GitHub Actions
        SLACK_COLOR: '#EC4926'
        SLACK_ICON_EMOJI: ':github:'
        SLACK_MESSAGE: 'Auth (release) build'
        SLACK_TITLE: 'Build failed :fire:'